no cache

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -54,17 +54,12 @@ fi
 # Check if FVM is installed
 if ! command -v fvm &> /dev/null; then
   echo "FVM is not installed. Installing FVM..."
-  dart pub global activate fvm
+  dart pub global activate fvm || { echo "Failed to activate FVM"; exit 1; }
   export PATH="$PATH":"$HOME/.pub-cache/bin"
 fi
 
-if [ -d "$CACHE_DIR/flutter" ]; then
-  print "Restoring Flutter SDK from CACHE"
-  cp -R $CACHE_DIR/flutter $BUILD_DIR
-else
-  print "Installing SDK from Github repository."
-  git clone https://github.com/flutter/flutter.git --quiet
-fi
+print "Installing SDK from Github repository."
+git clone https://github.com/flutter/flutter.git --quiet
 
 # Check if FLUTTER_VERSION variables is set.
 if [ -n "$FLUTTER_VERSION" ]; then
