--no-version-check not working

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -66,13 +66,13 @@ rm $FLUTTER_ARCHIVE
 export PATH="$BUILD_DIR/flutter/bin:$PATH"
 
 print "Enabling web support"
-flutter config --enable-web --no-version-check || fail "Failed to enable web support"
+flutter config --enable-web || fail "Failed to enable web support"
 
 print "Running flutter clean"
-flutter clean --no-version-check || fail "Flutter clean failed"
+flutter clean || fail "Flutter clean failed"
 
 print "Getting flutter packages"
-flutter pub get --no-version-check || fail "Failed to get packages"
+flutter pub get || fail "Failed to get packages"
 
 if [ -z "$FLUTTER_BUILD" ]; then
   if [ "$ENVIRONMENT" = "prod" ]; then
