FLUTTER_UPGRADE=false

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -66,13 +66,13 @@ rm $FLUTTER_ARCHIVE
 export PATH="$BUILD_DIR/flutter/bin:$PATH"
 
 print "Enabling Web support"
-flutter config --enable-web --no-version-check || fail "Failed to enable web support"
+FLUTTER_UPGRADE=false flutter config --enable-web || fail "Failed to enable web support"
 
 print "Running flutter clean"
-flutter clean --no-version-check || fail "Flutter clean failed"
+FLUTTER_UPGRADE=false flutter clean || fail "Flutter clean failed"
 
 print "Getting Flutter packages"
-flutter pub get --no-version-check || fail "Failed to get packages"
+FLUTTER_UPGRADE=false flutter pub get || fail "Failed to get packages"
 
 if [ -z "$FLUTTER_BUILD" ]; then
   if [ "$ENVIRONMENT" = "prod" ]; then
@@ -83,7 +83,7 @@ if [ -z "$FLUTTER_BUILD" ]; then
 fi
 
 print "Building Flutter project with: $FLUTTER_BUILD"
-eval $FLUTTER_BUILD --no-version-check || fail "Flutter build failed"
+FLUTTER_UPGRADE=false eval $FLUTTER_BUILD || fail "Flutter build failed"
 
 print "Cleaning up unnecessary files"
 rm -rf $BUILD_DIR/flutter
