--no-version-check 3

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -72,7 +72,7 @@ print "Running flutter clean"
 flutter clean --no-version-check || fail "Flutter clean failed"
 
 print "Getting flutter packages"
-flutter pub get || fail "Failed to get packages"
+flutter pub get --no-version-check || fail "Failed to get packages"
 
 if [ -z "$FLUTTER_BUILD" ]; then
   if [ "$ENVIRONMENT" = "prod" ]; then
